### ISSUE TITLE
Position of pie menus

### ISSUE THREAD

**Issue by rajq123** [oRazeD/PieMenusPlus#1]
The select mode pie menus is poorly organized. The position of X-ray Toggle and overlay toggle is very frustrating please increase their distance because each time i goto edit/object mode, i accidentally select X-ray or overlay, We use object/edit mode frequently therefore the object/edit mode should have more space but rather you narrow down. Similarly in Active tools pie menu, replace the select and tweak with Box select because it is the natural way of selection. I rarely used select and tweak and the top position of pie menu is easy to access.

**Comment by oRazeD** [comment]
Hello Raj, in user preferences you can turn on simple context pie, which
will remove those options only leaving them in the shading pie. Unless you
have the github version there is also the option to choose your default
selection type :)
