### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Vinc3r** [oRazeD/PieMenusPlus#2]
Hi! I'm just start testing your pie menus, which looks like very convenient, but I'm not able to find a documentation.

Does it exists? And if not, I suggest opening the Wiki here on Github, I can contribute to a page referecing all keymaps for example.

**Comment by oRazeD** [comment]
Yes, there is no documentation for Pies Plus... I rarely have a large excess of time and it's quite a boring process considering the quantity of menus.

I can open up the wiki later today and will probably contribute to it myself as well.

If I'm honest, I think the best way to learn pies is to just go down the list of keymaps and play with them 1 by 1 disabling the ones you don't like as you go.

**Comment by Vinc3r** [comment]
Yeah I understand, I know how time-consuming is need to maintain a doc. But I'm a RTFM guy 😀

Anyway do as you want, it's your addon ;)

**Comment by oRazeD** [comment]
Alright, the page is up. I am not sure how wiki pull requests work, but feel free to submit them any way you would like if you do end up writing anything. Ill probably get around to the bare minimum of documentation at _some_ point, lol. Ill close this issue for now 😉

**Comment by Vinc3r** [comment]
Thanks I will check this soon! (these last & next days i'm too busy)

**Comment by Vinc3r** [comment]
I don't forget my promise to contribute to the doc, I still just have'nt time yet to do it 😅 (this probably until last half of august)
